// This file would be auto-generated by:
// supabase gen types typescript --project-id ajcznltdbwvhmhgzufzv > src/types/supabase.ts
// Run: bun run generate:types
//
// Below is a hand-crafted version based on the known schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      agents: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          state: 'draft' | 'stopped' | 'starting' | 'running' | 'stopping' | 'error';
          soul_prompt: string | null;
          settings: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          name: string;
          state?: 'draft' | 'stopped' | 'starting' | 'running' | 'stopping' | 'error';
          soul_prompt?: string | null;
          settings?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          name?: string;
          state?: 'draft' | 'stopped' | 'starting' | 'running' | 'stopping' | 'error';
          soul_prompt?: string | null;
          settings?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'agents_owner_id_fkey';
            columns: ['owner_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      agent_messages: {
        Row: {
          id: string;
          agent_id: string;
          peer: string;
          role: string;
          content: string;
          direction: 'incoming' | 'outgoing' | null;
          thread_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          agent_id: string;
          peer: string;
          role: string;
          content: string;
          direction?: 'incoming' | 'outgoing' | null;
          thread_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          agent_id?: string;
          peer?: string;
          role?: string;
          content?: string;
          direction?: 'incoming' | 'outgoing' | null;
          thread_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      agent_events: {
        Row: {
          id: string;
          agent_id: string;
          event_type: string;
          status: 'pending' | 'running' | 'succeeded' | 'failed' | 'cancelled';
          error: string | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          agent_id: string;
          event_type: string;
          status?: 'pending' | 'running' | 'succeeded' | 'failed' | 'cancelled';
          error?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          agent_id?: string;
          event_type?: string;
          status?: 'pending' | 'running' | 'succeeded' | 'failed' | 'cancelled';
          error?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      agent_onboarding_sessions: {
        Row: {
          id: string;
          owner_id: string;
          agent_name: string | null;
          soul_prompt: string | null;
          authorization_status: 'not_started' | 'code_requested' | 'password_required' | 'authorized' | 'error';
          phone_number: string | null;
          completed_agent_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          agent_name?: string | null;
          soul_prompt?: string | null;
          authorization_status?: 'not_started' | 'code_requested' | 'password_required' | 'authorized' | 'error';
          phone_number?: string | null;
          completed_agent_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          agent_name?: string | null;
          soul_prompt?: string | null;
          authorization_status?: 'not_started' | 'code_requested' | 'password_required' | 'authorized' | 'error';
          phone_number?: string | null;
          completed_agent_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      telegram_sessions: {
        Row: {
          id: string;
          agent_id: string;
          phone_number: string | null;
          authorization_status: 'not_started' | 'code_requested' | 'password_required' | 'authorized' | 'error' | 'revoked';
          last_authorized_at: string | null;
          last_error: string | null;
          api_id: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          agent_id: string;
          phone_number?: string | null;
          authorization_status?: 'not_started' | 'code_requested' | 'password_required' | 'authorized' | 'error' | 'revoked';
          last_authorized_at?: string | null;
          last_error?: string | null;
          api_id?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          agent_id?: string;
          phone_number?: string | null;
          authorization_status?: 'not_started' | 'code_requested' | 'password_required' | 'authorized' | 'error' | 'revoked';
          last_authorized_at?: string | null;
          last_error?: string | null;
          api_id?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      message_threads: {
        Row: {
          id: string;
          agent_id: string;
          peer: string;
          peer_name: string | null;
          message_count: number;
          last_message_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          agent_id: string;
          peer: string;
          peer_name?: string | null;
          message_count?: number;
          last_message_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          agent_id?: string;
          peer?: string;
          peer_name?: string | null;
          message_count?: number;
          last_message_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          email: string | null;
          display_name: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      agent_state: 'draft' | 'stopped' | 'starting' | 'running' | 'stopping' | 'error';
      event_status: 'pending' | 'running' | 'succeeded' | 'failed' | 'cancelled';
      auth_status: 'not_started' | 'code_requested' | 'password_required' | 'authorized' | 'error' | 'revoked';
    };
    CompositeTypes: Record<string, never>;
  };
}
